name: average
description: Calculate averages for classes
version: 0.0.1
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  _discoveryapis_commons: ^0.1.0
  angular2: ^2.2.0
  http: ^0.11.0
  http_server: ^0.9.5+1
  csv: ^3.1.1
  rpc: ^0.5.0
  test: ^0.12.18
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--show-package-warnings=average, --enable-experimental-mirrors]
